### PR TITLE
Add `Project.toml` w compat entries

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by kburns** [comment]
I don't know much about julia packaging, but if we aren't trying to register this as an official package, are the toml files necessary? A 1000 line manifest file completely unrelated to the source code seems a little... bloated?

**Comment by navidcy** [comment]
Only for reproducibility purposes. E.g., `using CubedSphere` in 2 months might be loading v1.2.3 with breaking changes.

But I see your point. We could just have a `Project.toml` with strict compat reqs. Let me do that ;)

**Comment by navidcy** [comment]
Did it. Or feel free to close it. :)

**Comment by kburns** [comment]
Thanks!

**Pull request merged**
